# Generated by Django 5.2.4 on 2025-07-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_todo_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
