# Generated by Django 5.2.4 on 2025-07-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
